version: '3.8'

services:
  javascript:
    build:
      context: .
    image: 'templates/javascript'
    container_name: javascript
    restart: on-failure
    port:
      - "9229:9229"
    volumes:
      - ./source:/app
    command: 'npm run start:debug'
