env:
  browser: true
  es2021: true
  jest: true
# extends:
#   - plugin:vue/vue3-essential
#   - airbnb
#   - airbnb-typescript,
#   - plugin:import/typescript
#   # - standard-with-typescript
#   - plugin:prettier/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  # project: ./tsconfig.json
  ecmaFeatures:
    jsx": true
plugins:
  - vue
  - prettier
  - '@typescript-eslint'
rules:
  semi:
    - error
    - "always"
  quotes:
    - error
    - "double"
  prefer-const: error
