version: '3.8'

services:
  python:
    build:
      context: .
    image: templates/python
    container_name: python
    restart: on-failure
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      PYDEVD_DISABLE_FILE_VALIDATION: 1
    ports:
      - '5678:5678'
    volumes:
      - .:/app
    # command: 'python -m main'
    command: 'python -m debugpy --listen 0.0.0.0:5678 -m main'
